### ISSUE TITLE
initial value is not formatted

### ISSUE THREAD

**Issue by vrubliuk** [GoncharukOrg/react-input#37]
```ts
import { useNumberFormat, InputNumberFormat } from "@react-input/number-format";
import { useState } from "react";

function App() {
  const inputRef = useNumberFormat({ locales: "en", minimumFractionDigits: 2 });
  const [value, setValue] = useState("10000");

  return (
    <input
      ref={inputRef}
      value={value}
      onChange={(e) => setValue(e.target.value)}
    />
  );
}

// expected initial value in the input: "10,000.00"
// actual initial value in the input: "10000"
```

**Comment by GoncharukBro** [comment]
To support the concept of controlled input, `@react-input/number-format` does not modify the value passed in the `value` property of the `input` element, meaning that the value in the state exactly matches the value in the `input` element. 

In controlled input, when the input value is not formatted, you should use the `format` utility described in the chapter «[Utils](https://github.com/GoncharukOrg/react-input/tree/main/packages/number-format#utils)» to substitute the correct value, for example:

```tsx
import { useState } from 'react';
import { useNumberFormat, format } from '@react-input/number-format';

const options = { locales: 'en', maximumFractionDigits: 2 };

export default function App() {
  const inputRef = useNumberFormat(options);
  const defaultValue = format("10000", options);

  const [value, setValue] = useState(defaultValue); // `defaultValue` or '123,456,789'

  return <input ref={inputRef} value={value} onChange={(event) => setValue(event.target.value)} />;
}
```

Information for reference: https://github.com/GoncharukOrg/react-input/tree/main/packages/number-format#initializing-the-value

**Comment by vrubliuk** [comment]
Thanks for the explanation. 
This solution works when a default value is hardcoded on front-end.
But it doesn't seem helpful when default values are asynchronically fetched from a back-end.
It would be great if this library could handle such cases as well. (for example, like this one does https://s-yadav.github.io/react-number-format/docs/numeric_format)

**Comment by GoncharukBro** [comment]
We intentionally do not add automatic formatting for controlled input in order not to create precedents when the state is not equal to the actual value, which can predictably lead to confusion, since it violates the principle of input control, as well as allowing bugs. At the same time, automatic formatting is present only for uncontrolled input, which makes working with input safer.
