### ISSUE TITLE
Error instaling via npm

### ISSUE THREAD

**Issue by Andreibv** [GoncharukOrg/react-input#38]
When installing via npm, im getting this error:
But i think that downgrade is unsafe.

npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!   peer react@">=16.8" from @react-input/number-format@1.1.1
npm ERR!   node_modules/@react-input/number-format
npm ERR!     @react-input/number-format@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.3.1" from react-dom@18.3.1
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@">=16.8" from @react-input/number-format@1.1.1

**Comment by GoncharukBro** [comment]
Please tell us what dependencies you use during installation or send us a repository with the code.

**Comment by JoseDRojasA** [comment]
@GoncharukBro I'm having this same issue after upgrading to nextjs 15

**Comment by GoncharukBro** [comment]
We made changes in the latest version of the package. Please update the package:

```
npm i @react-input/number-format@latest
```
