### ISSUE TITLE
SyntaxError Cannot convert - to a BigInt in NumberFormat package when user types "-" as the first char 

### ISSUE THREAD

**Issue by walkernel** [GoncharukOrg/react-input#41]
When using the NumberFormatting package and a user types in a - as their first character, SyntaxError Cannot convert - to a BigInt occurs.

To reproduce:
- open the codesandbox listed in the NumberFormat readme
https://codesandbox.io/p/sandbox/react-input-number-format-r234d9?file=%2Fsrc%2FApp.tsx
type - in the input field

**Comment by GoncharukBro** [comment]
Thanks for pointing out the error, the fix is ​​already available in the new version.
